version: '3.8'

services:
  db:
    image: postgres:12-alpine
    container_name: postgres-container
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: project
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data 


volumes:
  postgres_data:
    driver: local  